-- Luanti
-- SPDX-License-Identifier: LGPL-2.1-or-later
-- Copyright (C) 2026 The Luanti Contributors

-- The showcase palette: a short, intentional set of nodes that read as
-- architecture and exhibition design rather than a museum of drawtypes.
--
-- Everything here is deliberately GLES2/WebGL friendly: 16x16 tiles, no
-- connected textures, no mesh nodes, no shader tricks. Animated tiles are
-- vertical filmstrips, which the browser renderer handles the same way it
-- handles water in any other game.
--
-- Textures are generated by util/content/generate_luanti_web_textures.py.

lw_nodes = {}

-- 16 dyed cubes. One greyscale weave tinted with [multiply, so the whole
-- palette costs a single 16x16 texture instead of sixteen.
lw_nodes.wool_colors = {
	{name = "white", desc = "White", hex = "#e9e9e4"},
	{name = "grey", desc = "Grey", hex = "#9a9a95"},
	{name = "dark_grey", desc = "Dark Grey", hex = "#4c4c48"},
	{name = "black", desc = "Black", hex = "#1c1c1a"},
	{name = "red", desc = "Red", hex = "#bf2f31"},
	{name = "orange", desc = "Orange", hex = "#e07a22"},
	{name = "yellow", desc = "Yellow", hex = "#e6c22f"},
	{name = "green", desc = "Green", hex = "#5aa83c"},
	{name = "dark_green", desc = "Dark Green", hex = "#2d6b2d"},
	{name = "cyan", desc = "Cyan", hex = "#31b0ae"},
	{name = "blue", desc = "Blue", hex = "#2f5cba"},
	{name = "violet", desc = "Violet", hex = "#6c3fb8"},
	{name = "magenta", desc = "Magenta", hex = "#b43196"},
	{name = "pink", desc = "Pink", hex = "#e38cae"},
	{name = "brown", desc = "Brown", hex = "#7b5230"},
	{name = "tan", desc = "Tan", hex = "#c8a97a"},
}

function lw_nodes.wool_texture(hex)
	return "lw_wool.png^[multiply:" .. hex
end

-- Every palette node carries lw_palette so the material library can list the
-- set without hardcoding names, and so a future kit item stays in sync.
local function palette_groups(groups)
	local out = {lw_palette = 1}
	for key, value in pairs(groups or {}) do
		out[key] = value
	end
	return out
end

local function register(name, def)
	def.groups = palette_groups(def.groups)
	if def.is_ground_content == nil then
		def.is_ground_content = false
	end
	core.register_node("lw_nodes:" .. name, def)
end

--------------------------------------------------------------------------
-- Ground and terrain
--------------------------------------------------------------------------

register("stone", {
	description = "Stone",
	tiles = {"lw_stone.png"},
	groups = {cracky = 3},
	is_ground_content = true,
})

register("dirt", {
	description = "Dirt",
	tiles = {"lw_dirt.png"},
	groups = {crumbly = 3, soil = 1},
	is_ground_content = true,
})

register("dirt_with_grass", {
	description = "Dirt with Grass",
	tiles = {
		"lw_grass_top.png",
		"lw_dirt.png",
		{name = "lw_grass_side.png", tileable_vertical = false},
	},
	groups = {crumbly = 3, soil = 1},
	is_ground_content = true,
})

register("sand", {
	description = "Sand",
	tiles = {"lw_sand.png"},
	groups = {crumbly = 3, falling_node = 0},
	is_ground_content = true,
})

register("paving", {
	description = "Plaza Paving",
	tiles = {"lw_paving.png"},
	groups = {cracky = 3},
})

register("water", {
	description = "Water",
	drawtype = "liquid",
	waving = 3,
	tiles = {{
		name = "lw_water.png",
		backface_culling = false,
		animation = {type = "vertical_frames", aspect_w = 16, aspect_h = 16, length = 2.0},
	}},
	special_tiles = {
		{
			name = "lw_water.png",
			backface_culling = false,
			animation = {type = "vertical_frames", aspect_w = 16, aspect_h = 16, length = 2.0},
		},
		{
			name = "lw_water.png",
			backface_culling = true,
			animation = {type = "vertical_frames", aspect_w = 16, aspect_h = 16, length = 2.0},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	drowning = 1,
	liquidtype = "source",
	liquid_alternative_source = "lw_nodes:water",
	liquid_alternative_flowing = "lw_nodes:water",
	liquid_viscosity = 1,
	liquid_renewable = false,
	liquid_range = 0,
	post_effect_color = {a = 64, r = 60, g = 110, b = 170},
	groups = {water = 3, liquid = 3},
})

--------------------------------------------------------------------------
-- Structure
--------------------------------------------------------------------------

register("stone_brick", {
	description = "Stone Brick",
	tiles = {"lw_stone_brick.png"},
	groups = {cracky = 2},
})

register("polished_stone", {
	description = "Polished Stone",
	tiles = {"lw_polished_stone.png"},
	groups = {cracky = 2},
})

register("planks", {
	description = "Wood Planks",
	tiles = {"lw_planks.png"},
	groups = {choppy = 2, oddly_breakable_by_hand = 2, flammable = 0},
})

register("beam", {
	description = "Timber Beam",
	tiles = {"lw_beam_end.png", "lw_beam_end.png", "lw_beam_side.png"},
	paramtype2 = "facedir",
	on_place = core.rotate_node,
	groups = {choppy = 2},
})

register("glass", {
	description = "Glass",
	drawtype = "glasslike",
	tiles = {"lw_glass.png"},
	use_texture_alpha = "blend",
	paramtype = "light",
	sunlight_propagates = true,
	groups = {cracky = 3},
})

register("bars", {
	description = "Iron Bars",
	drawtype = "nodebox",
	tiles = {"lw_bars.png"},
	use_texture_alpha = "clip",
	paramtype = "light",
	paramtype2 = "facedir",
	sunlight_propagates = true,
	on_place = core.rotate_node,
	node_box = {type = "fixed", fixed = {-0.5, -0.5, -0.0625, 0.5, 0.5, 0.0625}},
	selection_box = {type = "fixed", fixed = {-0.5, -0.5, -0.0625, 0.5, 0.5, 0.0625}},
	groups = {cracky = 2},
})

register("gold_trim", {
	description = "Gold Trim",
	tiles = {"lw_gold.png"},
	groups = {cracky = 2},
})

--------------------------------------------------------------------------
-- Architecture
--------------------------------------------------------------------------

-- Plain fixed nodeboxes. No connected textures: WebGL is happier and the
-- browser client does not have to ship a second tile set per material.
local function register_stair_and_slab(base, description, tiles, groups)
	register("stair_" .. base, {
		description = description .. " Stair",
		drawtype = "nodebox",
		tiles = tiles,
		paramtype = "light",
		paramtype2 = "facedir",
		on_place = core.rotate_node,
		node_box = {
			type = "fixed",
			fixed = {
				{-0.5, -0.5, -0.5, 0.5, 0.0, 0.5},
				{-0.5, 0.0, 0.0, 0.5, 0.5, 0.5},
			},
		},
		groups = groups,
	})
	register("slab_" .. base, {
		description = description .. " Slab",
		drawtype = "nodebox",
		tiles = tiles,
		paramtype = "light",
		node_box = {type = "fixed", fixed = {-0.5, -0.5, -0.5, 0.5, 0.0, 0.5}},
		groups = groups,
	})
end

register_stair_and_slab("stone_brick", "Stone Brick", {"lw_stone_brick.png"}, {cracky = 2})
register_stair_and_slab("planks", "Wood Plank", {"lw_planks.png"}, {choppy = 2})

register("column", {
	description = "Column",
	drawtype = "nodebox",
	tiles = {"lw_column_top.png", "lw_column_top.png", "lw_column_side.png"},
	paramtype = "light",
	node_box = {type = "fixed", fixed = {-0.375, -0.5, -0.375, 0.375, 0.5, 0.375}},
	groups = {cracky = 2},
})

register("fence", {
	description = "Fence",
	drawtype = "nodebox",
	tiles = {"lw_fence.png"},
	paramtype = "light",
	paramtype2 = "facedir",
	sunlight_propagates = true,
	on_place = core.rotate_node,
	node_box = {
		type = "fixed",
		fixed = {
			{-0.125, -0.5, -0.125, 0.125, 0.5, 0.125},
			{-0.5, 0.0, -0.0625, 0.5, 0.3125, 0.0625},
			{-0.5, -0.3125, -0.0625, 0.5, 0.0, 0.0625},
		},
	},
	groups = {choppy = 2},
})

register("curtain", {
	description = "Velvet Curtain",
	tiles = {"lw_curtain.png"},
	groups = {snappy = 2, oddly_breakable_by_hand = 2},
})

register("carpet", {
	description = "Carpet",
	drawtype = "nodebox",
	tiles = {"lw_carpet.png"},
	paramtype = "light",
	node_box = {type = "fixed", fixed = {-0.5, -0.5, -0.5, 0.5, -0.4375, 0.5}},
	groups = {snappy = 3, oddly_breakable_by_hand = 3},
})

--------------------------------------------------------------------------
-- Lighting
--------------------------------------------------------------------------

register("lamp", {
	description = "Ceiling Lamp",
	tiles = {"lw_lamp.png"},
	paramtype = "light",
	light_source = 14,
	groups = {cracky = 3},
})

register("uplight", {
	description = "Floor Uplight",
	drawtype = "nodebox",
	tiles = {"lw_uplight.png"},
	paramtype = "light",
	light_source = 12,
	node_box = {type = "fixed", fixed = {-0.3125, -0.5, -0.3125, 0.3125, -0.25, 0.3125}},
	groups = {cracky = 3},
})

-- An invisible light so a gallery can be lit without a visible fixture.
register("hidden_light", {
	description = "Hidden Light",
	drawtype = "airlike",
	inventory_image = "lw_hidden_light.png",
	wield_image = "lw_hidden_light.png",
	paramtype = "light",
	light_source = 14,
	sunlight_propagates = true,
	walkable = false,
	pointable = true,
	buildable_to = false,
	groups = {dig_immediate = 3},
})

--------------------------------------------------------------------------
-- Exhibition
--------------------------------------------------------------------------

register("pedestal", {
	description = "Pedestal",
	drawtype = "nodebox",
	tiles = {"lw_pedestal_top.png", "lw_pedestal_top.png", "lw_pedestal_side.png"},
	paramtype = "light",
	node_box = {
		type = "fixed",
		fixed = {
			{-0.4375, -0.5, -0.4375, 0.4375, -0.375, 0.4375},
			{-0.3125, -0.375, -0.3125, 0.3125, 0.375, 0.3125},
			{-0.4375, 0.375, -0.4375, 0.4375, 0.5, 0.4375},
		},
	},
	groups = {cracky = 2},
})

register("frame", {
	description = "Frame Moulding",
	tiles = {"lw_frame.png"},
	groups = {choppy = 2, oddly_breakable_by_hand = 2},
})

-- A thin panel that hangs on a wall.
--
-- Tile order is +Y, -Y, +X, -X, +Z, -Z, so the art goes on index 6 and the box
-- hugs the -Z side of the node: at facedir 0 the panel faces south, which is
-- the direction a visitor walking north through this world is looking from.
local function register_panel(name, description, front, groups)
	register(name, {
		description = description,
		drawtype = "nodebox",
		tiles = {"lw_frame.png", "lw_frame.png", "lw_frame.png", "lw_frame.png",
			"lw_frame.png", front},
		paramtype = "light",
		paramtype2 = "facedir",
		sunlight_propagates = true,
		on_place = core.rotate_node,
		node_box = {type = "fixed", fixed = {-0.5, -0.5, -0.5, 0.5, 0.5, -0.4375}},
		groups = groups,
	})
end

register_panel("poster", "Poster", "lw_poster.png",
	{choppy = 2, oddly_breakable_by_hand = 2})

register("stanchion", {
	description = "Rope Stanchion",
	drawtype = "nodebox",
	tiles = {"lw_stanchion.png"},
	use_texture_alpha = "clip",
	paramtype = "light",
	sunlight_propagates = true,
	node_box = {type = "fixed", fixed = {-0.1875, -0.5, -0.1875, 0.1875, 0.25, 0.1875}},
	selection_box = {type = "fixed", fixed = {-0.1875, -0.5, -0.1875, 0.1875, 0.25, 0.1875}},
	groups = {cracky = 3},
})

-- Animated LED surface for the kinetic courtyard (and any ticker wall).
register("ticker", {
	description = "LED Ticker Panel",
	tiles = {{
		name = "lw_ticker.png",
		animation = {type = "vertical_frames", aspect_w = 16, aspect_h = 16, length = 1.6},
	}},
	light_source = 8,
	groups = {cracky = 3},
})

--------------------------------------------------------------------------
-- Dyed cubes
--------------------------------------------------------------------------

for _, color in ipairs(lw_nodes.wool_colors) do
	register("wool_" .. color.name, {
		description = color.desc .. " Wool",
		tiles = {lw_nodes.wool_texture(color.hex)},
		groups = {snappy = 2, oddly_breakable_by_hand = 3, lw_wool = 1},
	})
end

--------------------------------------------------------------------------
-- Mapgen aliases
--------------------------------------------------------------------------

-- The showcase world is authored on top of singlenode; these aliases only
-- matter if somebody creates a world with another mapgen.
core.register_alias("mapgen_singlenode", "air")
core.register_alias("mapgen_stone", "lw_nodes:stone")
core.register_alias("mapgen_water_source", "lw_nodes:water")
core.register_alias("mapgen_river_water_source", "lw_nodes:water")
core.register_alias("mapgen_dirt", "lw_nodes:dirt")
core.register_alias("mapgen_dirt_with_grass", "lw_nodes:dirt_with_grass")
core.register_alias("mapgen_sand", "lw_nodes:sand")
core.register_alias("mapgen_cobble", "lw_nodes:stone_brick")
core.register_alias("mapgen_stair_cobble", "lw_nodes:stair_stone_brick")
